apply plugin: 'com.android.application'

android {
    compileSdkVersion 30

    defaultConfig {
        applicationId "com.vir.brower"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 54546145
        versionName "1.4.5-power-x-marmalade"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    // Оставляем только то, что на 100% стабильно и никогда не создает пустых XML-файлов
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.webkit:webkit:1.6.0'
}

